# Server configuration
server.port=8080

# Student specific configurations (Can be modified as needed)
bfhl.user.id=harshit_nijhawan_24062026
bfhl.email=harshit0876.be23@chitkara.edu.in
bfhl.roll.number=2310990876
